In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv('clean_dataset_stem.csv', sep=';')

In [5]:
dataset.shape #menampilkan jumlah baris dan kolom

(902, 10)

In [6]:
#menampilkan nama-nama kolom
dataset.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'Tweet', 'Sentimen', 'step01', 'tokens',
       'final_tokens', 'step02', 'finalText_str', 'ProcessedText'],
      dtype='object')

In [7]:
dataset.head(10) #menampilkan 10 baris pertama 

Unnamed: 0.1  Unnamed: 0  \
0             0           0   
1             1           1   
2             2           2   
3             3           3   
4             4           4   
5             5           5   
6             6           6   
7             7           7   
8             8           8   
9             9           9   

                                               Tweet  Sentimen  \
0  Cegah mata rantai Covid-19,mari kita dirumah s...       1.0   
1  aku mohon yaAllah semoga wabah covid-19 menghi...       1.0   
2  Pemprov Papua Naikkan Status Jadi Tanggap Daru...       1.0   
3            Covid belum nyampe prigen mbak hmm hoax       0.0   
4  Nyuruh orang pintar, lu aja Togog. Itu kerumun...      -1.0   
5  Pikir2 balik byk mnde plk nk setelkn lepas covid.       0.0   
6  Selamat pagi, hari jum'at. Jum'at keempat di k...       1.0   
7  Hikmah di balik musibah covid-19, smg para pej...       1.0   
8  Cegah covid-19 beserta jajaran Polsek Kuranji ...       1.0   
9  Ya Allah kami memohon pada mu perkenankanlah d...       1.0   

                                              step01  \
0  cegah mata rantai covid   mari kita dirumah sa...   
1  aku mohon yaallah semoga wabah covid   menghil...   
2  pemprov papua naikkan status jadi tanggap daru...   
3            covid belum nyampe prigen mbak hmm hoax   
4  nyuruh orang pintar lu aja togog itu kerumunan...   
5    pikir balik byk mnde plk nk setelkn lepas covid   
6  selamat pagi hari jumat jumat keempat di kala ...   
7  hikmah di balik musibah covid   smg para pejab...   
8  cegah covid   beserta jajaran polsek kuranji m...   
9  ya allah kami memohon pada mu perkenankanlah d...   

                                              tokens  \
0  ['cegah', 'mata', 'rantai', 'covid', 'mari', '...   
1  ['aku', 'mohon', 'yaallah', 'semoga', 'wabah',...   
2  ['pemprov', 'papua', 'naikkan', 'status', 'jad...   
3  ['covid', 'belum', 'nyampe', 'prigen', 'mbak',...   
4  ['nyuruh', 'orang', 'pintar', 'lu', 'aja', 'to...   
5  ['pikir', 'balik', 'byk', 'mnde', 'plk', 'nk',...   
6  ['selamat', 'pagi', 'hari', 'jumat', 'jumat', ...   
7  ['hikmah', 'di', 'balik', 'musibah', 'covid', ...   
8  ['cegah', 'covid', 'beserta', 'jajaran', 'pols...   
9  ['ya', 'allah', 'kami', 'memohon', 'pada', 'mu...   

                                        final_tokens  \
0  ['cegah', 'mata', 'rantai', 'covid', 'mari', '...   
1  ['aku', 'mohon', 'yaallah', 'semoga', 'wabah',...   
2  ['pemprov', 'papua', 'naikkan', 'status', 'jad...   
3  ['covid', 'belum', 'nyampe', 'prigen', 'mbak',...   
4  ['nyuruh', 'orang', 'pintar', 'lu', 'aja', 'to...   
5  ['pikir', 'balik', 'byk', 'mnde', 'plk', 'nk',...   
6  ['selamat', 'pagi', 'hari', 'jumat', 'jumat', ...   
7  ['hikmah', 'di', 'balik', 'musibah', 'covid', ...   
8  ['cegah', 'covid', 'beserta', 'jajaran', 'pols...   
9  ['ya', 'allah', 'kami', 'memohon', 'pada', 'mu...   

                                              step02  \
0  cegah mata rantai covid mari kita dirumah saja...   
1  aku mohon yaallah semoga wabah covid menghilan...   
2  pemprov papua naikkan status jadi tanggap daru...   
3            covid belum nyampe prigen mbak hmm hoax   
4  nyuruh orang pintar lu aja togog itu kerumunan...   
5    pikir balik byk mnde plk nk setelkn lepas covid   
6  selamat pagi hari jumat jumat keempat di kala ...   
7  hikmah di balik musibah covid smg para pejabat...   
8  cegah covid beserta jajaran polsek kuranji mel...   
9  ya allah kami memohon pada mu perkenankanlah d...   

                                       finalText_str  \
0  cegah mata rantai covid mari kita dirumah saja...   
1  aku mohon yaallah semoga wabah covid menghilan...   
2  pemprov papua naikkan status jadi tanggap daru...   
3            covid belum nyampe prigen mbak hmm hoax   
4  nyuruh orang pintar lu aja togog itu kerumunan...   
5    pikir balik byk mnde plk nk setelkn lepas covid   
6  selamat pagi hari jumat jumat keempat di kala ...   
7  hikmah di balik

In [12]:
# Memastikan semua data dalam kolom 'ProcessedText' bertipe string
dataset_feature = dataset['ProcessedText'].astype(str)

In [13]:
dataset_label = dataset['Sentimen']

In [14]:
dataset_feature

0      cegah mata rantai covid kita rumah hingga hari...
1      aku mohon yaallah moga wabah covid hilang rama...
2      pemprov papua naik status jadi tanggap darurat...
3                      covid nyampe prigen mbak hmm hoax
4      nyuruh orang pintar lu aja togog kerumun orang...
                             ...                        
897    seluruh negara dunia alami masa sulit covid ra...
898    covid skripsi disaster selesai mau bgt bljr ma...
899    malam projek benda bincang malam fb satu belia...
900                          pontang panting koyak covid
901    masalah sekarang isu jangkit covid alaaaa bosa...
Name: ProcessedText, Length: 902, dtype: object

In [15]:
dataset_label

0      1.0
1      1.0
2      1.0
3      0.0
4     -1.0
      ... 
897    1.0
898    1.0
899    0.0
900   -1.0
901   -1.0
Name: Sentimen, Length: 902, dtype: float64

BOW

In [16]:
# Mengimpor CountVectorizer dari sklearn untuk mengubah teks menjadi representasi numerik
from sklearn.feature_extraction.text import CountVectorizer

In [17]:
vectorizer = CountVectorizer()

In [18]:
X = vectorizer.fit_transform(dataset_feature)

In [22]:
print(vectorizer.get_feature_names_out())

['aa' 'aamiin' 'aamiingimana' ... 'zmn' 'zona' 'zone']


In [23]:
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [26]:
vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2,2))

In [27]:
X2 = vectorizer2.fit_transform(dataset_feature)

In [28]:
print(vectorizer2.get_feature_names_out())

['aa warga' 'aamiin aamiin' 'aamiin gimana' ... 'zmn pkp' 'zona hijau'
 'zone covid']


In [29]:
print(X2.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


SIMULASI CORPUS

In [30]:
corpus = [
    'Perawatan kulit yang baik dapat meningkatkan kesehatan dan penampilan kulit.',
    'Penting untuk memilih produk skincare yang sesuai dengan jenis kulit.',
    'Pembersihan wajah secara rutin adalah langkah awal dalam perawatan kulit.',
    'Sunscreen sangat penting untuk melindungi kulit dari paparan sinar UV.',
    'Serum vitamin C dapat membantu mencerahkan kulit dan mengurangi noda hitam.',
    'Moisturizer berfungsi menjaga kelembapan kulit sepanjang hari.',
    'Exfoliating membantu mengangkat sel-sel kulit mati dan membuat kulit tampak lebih segar.',
    'Penggunaan masker wajah dapat memberikan nutrisi tambahan bagi kulit.'
]

In [31]:
vectorizer = CountVectorizer()

In [32]:
Z = vectorizer.fit_transform(corpus)

In [33]:
vectorizer.get_feature_names_out()

array(['adalah', 'awal', 'bagi', 'baik', 'berfungsi', 'dalam', 'dan',
       'dapat', 'dari', 'dengan', 'exfoliating', 'hari', 'hitam', 'jenis',
       'kelembapan', 'kesehatan', 'kulit', 'langkah', 'lebih', 'masker',
       'mati', 'melindungi', 'membantu', 'memberikan', 'membuat',
       'memilih', 'mencerahkan', 'mengangkat', 'mengurangi',
       'meningkatkan', 'menjaga', 'moisturizer', 'noda', 'nutrisi',
       'paparan', 'pembersihan', 'penampilan', 'penggunaan', 'penting',
       'perawatan', 'produk', 'rutin', 'sangat', 'secara', 'segar', 'sel',
       'sepanjang', 'serum', 'sesuai', 'sinar', 'skincare', 'sunscreen',
       'tambahan', 'tampak', 'untuk', 'uv', 'vitamin', 'wajah', 'yang'],
      dtype=object)

In [34]:
print(Z.toarray())

[[0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 2 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
  1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
  0 0 1 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 1]
 [1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
  0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0
  0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 2 0 1 0 1 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 1 2 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0
  0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0]]


In [35]:
vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))

In [36]:
Z2 = vectorizer2.fit_transform(corpus)

In [37]:
vectorizer2.get_feature_names_out()

array(['adalah langkah', 'awal dalam', 'bagi kulit', 'baik dapat',
       'berfungsi menjaga', 'dalam perawatan', 'dan membuat',
       'dan mengurangi', 'dan penampilan', 'dapat membantu',
       'dapat memberikan', 'dapat meningkatkan', 'dari paparan',
       'dengan jenis', 'exfoliating membantu', 'jenis kulit',
       'kelembapan kulit', 'kesehatan dan', 'kulit dan', 'kulit dari',
       'kulit mati', 'kulit sepanjang', 'kulit tampak', 'kulit yang',
       'langkah awal', 'lebih segar', 'masker wajah', 'mati dan',
       'melindungi kulit', 'membantu mencerahkan', 'membantu mengangkat',
       'memberikan nutrisi', 'membuat kulit', 'memilih produk',
       'mencerahkan kulit', 'mengangkat sel', 'mengurangi noda',
       'meningkatkan kesehatan', 'menjaga kelembapan',
       'moisturizer berfungsi', 'noda hitam', 'nutrisi tambahan',
       'paparan sinar', 'pembersihan wajah', 'penampilan kulit',
       'penggunaan masker', 'penting untuk', 'perawatan kulit',
       'produk skincare

In [38]:
print(Z2.toarray())

[[0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
  0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 1]
 [1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
  0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0
  1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 0 1 0 0 1 0 1 0 0 1
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]